### ISSUE TITLE
사용자페이지 > main.html

### ISSUE THREAD

**Issue by seul5106** [gogleset/ezen_project#11]
![image](https://user-images.githubusercontent.com/62301236/154660712-459d43af-81e0-4fc5-8345-7f07303be5e0.png)

사용자 메인 페이지 event부분 안나옴

**Comment by gogleset** [comment]
아직 누나 작업안했나봐

**Comment by imdajung** [comment]
![image](https://user-images.githubusercontent.com/91589093/154725192-993d8d17-76a1-45e6-a6f9-70b2535f6c70.png)

참고 : 이벤트 배너 배경색 (teal)이 제거된 이미지입니다.

**Comment by imdajung** [comment]
![image](https://user-images.githubusercontent.com/91589093/154811285-c09e1d39-3076-4f0d-b6f8-ded524a80a1d.png)

<예시 이미지입니다>
